// ── PRÉTÉRIT & PRESENT PERFECT ────────────────────────────────────────────────
// Content extracted from: 182-Preterite_Present_Perfect/Section_1/MATCHTPS.TBK
// Original format: FR sentence left → draw line to correct EN translation (2 choices)

const TENSES_QUESTIONS = [
  {
    q: 'Le premier circuit intégré fut créé en 1959.',
    options: [
      { text: 'The first integrated circuit was created in 1959.', correct: true },
      { text: 'The first integrated circuit has been created in 1959.', correct: false },
    ],
  },
  {
    q: 'Nous programmons en Cobol depuis 1960.',
    options: [
      { text: 'We have been writing programs in Cobol since 1960.', correct: true },
      { text: 'We write programs in Cobol since 1960.', correct: false },
    ],
  },
  {
    q: "Aujourd'hui le PC est tombé en panne 2 fois.",
    options: [
      { text: 'Today the PC has crashed twice.', correct: true },
      { text: 'Today the PC crashed twice.', correct: false },
    ],
  },
  {
    q: 'Il travaille dans la Silicon Valley depuis dix ans.',
    options: [
      { text: 'He has been working in Silicon Valley for ten years.', correct: true },
      { text: 'He has worked in Silicon Valley since ten years.', correct: false },
    ],
  },
  {
    q: "L'ordinateur a traité des données pendant huit heures.",
    options: [
      { text: 'The computer processed data for eight hours.', correct: true },
      { text: 'The computer has processed data for eight hours.', correct: false },
    ],
  },
  {
    q: "J'ai changé mon mot de passe la semaine dernière.",
    options: [
      { text: 'I changed my password last week.', correct: true },
      { text: 'I have changed my password last week.', correct: false },
    ],
  },
  {
    q: 'Java a été introduit en 1995.',
    options: [
      { text: 'Java was introduced in 1995.', correct: true },
      { text: 'Java has been introduced in 1995.', correct: false },
    ],
  },
  {
    q: 'Depuis combien de temps est-il connecté ?',
    options: [
      { text: 'How long has he been connected for?', correct: true },
      { text: 'How long is he connected for?', correct: false },
    ],
  },
];

// ── 182-2 : Expression du temps II ────────────────────────────────────────────
// Content extracted from: 182-Preterite_Present_Perfect/Section_2/EXPTPS2.TBK

const EXPRESSION_SENTENCES = [
  {
    fr: 'Il a été programmeur pendant trois ans puis il a démissionné.',
    tense: 'preterite',
    en: 'He was a programmer for three years then he resigned.',
    why: 'Action terminée dans une période écoulée → Prétérit.',
  },
  {
    fr: 'Nous fabriquons des ordinateurs depuis dix ans.',
    tense: 'present_perfect',
    en: 'We have manufactured computers for ten years.',
    why: '"Depuis" + action qui continue jusqu\'au présent → Present Perfect.',
  },
  {
    fr: "Un nouveau type d'ordinateur a été introduit cette année.",
    tense: 'present_perfect',
    en: 'A new type of computer has been introduced this year.',
    why: '"Cette année" n\'est pas encore terminée → Present Perfect.',
  },
  {
    fr: 'Hier soir, il a laissé ses disquettes près du téléphone.',
    tense: 'preterite',
    en: 'Last night, he left his floppies near the phone.',
    why: '"Hier soir" est une indication temporelle précise → Prétérit.',
  },
  {
    fr: "Combien de temps l'imprimante est-elle restée en marche ?",
    tense: 'present_perfect',
    en: 'How long has the printer been left on?',
    why: 'Durée en lien avec le présent → Present Perfect.',
  },
  {
    fr: "L'ordinateur a été inventé au siècle dernier.",
    tense: 'preterite',
    en: 'The computer was invented last century.',
    why: '"Au siècle dernier" est une période révolue et précise → Prétérit.',
  },
  {
    fr: "J'ai étudié l'informatique.",
    tense: 'present_perfect',
    en: 'I have studied computer science.',
    why: 'Résultat toujours pertinent aujourd\'hui → Present Perfect.',
  },
  {
    fr: "Je n'ai pas utilisé le réseau.",
    tense: 'present_perfect',
    en: 'I have not used the network.',
    why: 'État toujours vrai au moment où je parle → Present Perfect.',
  },
  {
    fr: "J'ai installé un antivirus en mai.",
    tense: 'preterite',
    en: 'I installed an antivirus program in May.',
    why: '"En mai" est une indication temporelle précise → Prétérit.',
  },
  {
    fr: "J'ai acheté une imprimante.",
    tense: 'present_perfect',
    en: 'I have bought a printer.',
    why: "L'imprimante est encore là, l'action reste pertinente → Present Perfect.",
  },
];

// ── Lexique extrait de EXPTPS2.TBK ────────────────────────────────────────────
const TENSES_LEXICON = [
  { fr: 'alcool', en: 'alcohol' },
  { fr: 'antivirus', en: 'antivirus program' },
  { fr: 'appuyer sur une touche', en: 'to press a key' },
  { fr: 'au siècle dernier', en: 'last century' },
  { fr: 'bogue', en: 'bug' },
  { fr: 'chercher', en: 'to look for' },
  { fr: 'clavier', en: 'keyboard' },
  { fr: 'combien de temps', en: 'how long' },
  { fr: 'construire', en: 'to build' },
  { fr: 'convivial', en: 'user-friendly' },
  { fr: 'créer', en: 'to create' },
  { fr: 'démissionner', en: 'to resign' },
  { fr: 'démontrer', en: 'to show' },
  { fr: 'disquette', en: 'floppy disk' },
  { fr: 'encre', en: 'ink' },
  { fr: 'fabriquer', en: 'to manufacture' },
  { fr: 'habiter', en: 'to live' },
  { fr: 'hier soir', en: 'last night' },
  { fr: 'impressionner', en: 'to impress' },
  { fr: 'imprimante', en: 'printer' },
  { fr: "imprimante à jet d'encre", en: 'ink-jet printer' },
  { fr: 'informaticien', en: 'computer scientist' },
  { fr: 'informatique', en: 'computer science' },
  { fr: 'installer', en: 'to install' },
  { fr: 'introduire', en: 'to introduce' },
  { fr: 'laisser', en: 'to leave' },
  { fr: 'logiciel', en: 'software package' },
  { fr: 'machine à écrire', en: 'typewriter' },
  { fr: 'paire torsadée', en: 'twisted copper pair' },
  { fr: 'passer', en: 'to spend (time)' },
  { fr: 'programmeur', en: 'programmer' },
  { fr: 'puis', en: 'then' },
  { fr: 'réseau', en: 'network' },
  { fr: 'rester en marche', en: 'to be left on' },
  { fr: 'signer', en: 'to sign' },
  { fr: 'supprimer', en: 'to remove' },
  { fr: "système d'exploitation", en: 'operating system' },
  { fr: 'téléphone', en: 'telephone' },
  { fr: 'tomber en panne', en: 'to crash' },
  { fr: 'traitement de texte', en: 'word processor' },
  { fr: 'utiliser', en: 'to use' },
  { fr: 'vivre', en: 'to live' },
];

// ── Verbes irréguliers extraits de EXPTPS2.TBK ────────────────────────────────
const TENSES_VERBS = [
  { en: 'to abide, abode, abode', fr: 'rester fidèle à' },
  { en: 'to awake, awoke, awoken', fr: 'se réveiller' },
  { en: 'to be, was, been', fr: 'être' },
  { en: 'to be born, was born, been born', fr: 'naître' },
  { en: 'to bear, bore, borne', fr: 'porter' },
  { en: 'to beat, beat, beaten', fr: 'battre' },
  { en: 'to become, became, become', fr: 'devenir' },
  { en: 'to begin, began, begun', fr: 'commencer' },
  { en: 'to bend, bent, bent', fr: 'courber' },
  { en: 'to bet, bet, bet', fr: 'parier' },
  { en: 'to bid, bade, bid', fr: 'offrir, faire une offre' },
  { en: 'to bind, bound, bound', fr: 'lier' },
  { en: 'to bite, bit, bitten', fr: 'mordre' },
  { en: 'to bleed, bled, bled', fr: 'saigner' },
  { en: 'to blow, blew, blown', fr: 'souffler' },
  { en: 'to break, broke, broken', fr: 'briser, rompre' },
  { en: 'to breed, bred, bred', fr: 'reproduire, élever' },
  { en: 'to bring, brought, brought', fr: 'apporter' },
  { en: 'to build, built, built', fr: 'construire' },
  { en: 'to burn, burnt, burnt', fr: 'brûler' },
  { en: 'to burst, burst, burst', fr: 'éclater' },
  { en: 'to buy, bought, bought', fr: 'acheter' },
  { en: 'to cast, cast, cast', fr: 'jeter, lancer' },
  { en: 'to catch, caught, caught', fr: 'attraper' },
  { en: 'to chide, chid, chidden', fr: 'gronder, réprimander' },
  { en: 'to choose, chose, chosen', fr: 'choisir' },
  { en: 'to cling, clung, clung', fr: "s'accrocher" },
  { en: 'to come, came, come', fr: 'venir' },
  { en: 'to cost, cost, cost', fr: 'coûter' },
  { en: 'to creep, crept, crept', fr: 'ramper' },
  { en: 'to cut, cut, cut', fr: 'couper' },
  { en: 'to dare, dared, dared', fr: 'oser' },
  { en: 'to deal, dealt, dealt', fr: 'distribuer, traiter' },
  { en: 'to dig, dug, dug', fr: 'creuser' },
  { en: 'to do, did, done', fr: 'faire' },
  { en: 'to draw, drew, drawn', fr: 'dessiner, tirer' },
  { en: 'to dream, dreamt, dreamt', fr: 'rêver' },
  { en: 'to drink, drank, drunk', fr: 'boire' },
  { en: 'to drive, drove, driven', fr: 'conduire' },
  { en: 'to eat, ate, eaten', fr: 'manger' },
  { en: 'to fall, fell, fallen', fr: 'tomber' },
  { en: 'to feed, fed, fed', fr: 'nourrir' },
  { en: 'to feel, felt, felt', fr: 'ressentir' },
  { en: 'to fight, fought, fought', fr: 'se battre' },
  { en: 'to find, found, found', fr: 'trouver' },
  { en: 'to flee, fled, fled', fr: 'fuir' },
  { en: 'to fling, flung, flung', fr: 'lancer, jeter violemment' },
  { en: 'to fly, flew, flown', fr: 'voler' },
  { en: 'to forbid, forbade, forbidden', fr: 'interdire' },
  { en: 'to forget, forgot, forgotten', fr: 'oublier' },
  { en: 'to forgive, forgave, forgiven', fr: 'pardonner' },
  { en: 'to freeze, froze, frozen', fr: 'geler' },
  { en: 'to get, got, got', fr: 'obtenir' },
  { en: 'to give, gave, given', fr: 'donner' },
  { en: 'to go, went, gone', fr: 'aller' },
  { en: 'to grind, ground, ground', fr: 'moudre' },
  { en: 'to grow, grew, grown', fr: 'grandir, pousser' },
  { en: 'to hang, hung, hung', fr: 'pendre' },
  { en: 'to have, had, had', fr: 'avoir' },
  { en: 'to hear, heard, heard', fr: 'entendre' },
  { en: 'to hew, hewed, hewn', fr: 'tailler' },
  { en: 'to hide, hid, hidden', fr: 'cacher' },
  { en: 'to hit, hit, hit', fr: 'frapper' },
  { en: 'to hold, held, held', fr: 'tenir' },
  { en: 'to hurt, hurt, hurt', fr: 'blesser' },
  { en: 'to keep, kept, kept', fr: 'garder' },
  { en: 'to kneel, knelt, knelt', fr: "s'agenouiller" },
  { en: 'to knit, knit, knit', fr: 'tricoter' },
  { en: 'to know, knew, known', fr: 'savoir, connaître' },
  { en: 'to lay, laid, laid', fr: 'poser' },
  { en: 'to lead, led, led', fr: 'mener' },
  { en: 'to lean, leant, leant', fr: "se pencher, s'appuyer" },
  { en: 'to leap, leapt, leapt', fr: 'sauter' },
  { en: 'to learn, learnt, learnt', fr: 'apprendre' },
  { en: 'to leave, left, left', fr: 'laisser, partir' },
  { en: 'to lend, lent, lent', fr: 'prêter' },
  { en: 'to let, let, let', fr: 'laisser' },
  { en: 'to lie, lay, lain', fr: "être allongé, s'allonger" },
  { en: 'to light, lit, lit', fr: 'allumer, éclairer' },
  { en: 'to lose, lost, lost', fr: 'perdre' },
  { en: 'to make, made, made', fr: 'faire, fabriquer' },
  { en: 'to mean, meant, meant', fr: 'signifier, vouloir dire' },
  { en: 'to meet, met, met', fr: 'rencontrer, se réunir' },
  { en: 'to mow, mowed, mown', fr: 'faucher, tondre' },
  { en: 'to overgrow, overgrew, overgrown', fr: 'recouvrir de végétation' },
  { en: 'to overhang, overhung, overhung', fr: 'surplomber' },
  { en: 'to overrun, overran, overrun', fr: 'envahir' },
  { en: 'to overtake, overtook, overtaken', fr: 'dépasser, rattraper' },
  { en: 'to pay, paid, paid', fr: 'payer' },
  { en: 'to put, put, put', fr: 'mettre, poser' },
  { en: 'to read, read, read', fr: 'lire' },
  { en: 'to ride, rode, ridden', fr: 'aller à cheval / bicyclette' },
  { en: 'to ring, rang, rung', fr: 'sonner' },
  { en: 'to rise, rose, risen', fr: 'se lever' },
  { en: 'to run, ran, run', fr: 'courir' },
  { en: 'to saw, sawed, sawn', fr: 'scier' },
  { en: 'to say, said, said', fr: 'dire' },
  { en: 'to see, saw, seen', fr: 'voir' },
  { en: 'to seek, sought, sought', fr: 'chercher' },
  { en: 'to sell, sold, sold', fr: 'vendre' },
  { en: 'to send, sent, sent', fr: 'envoyer' },
  { en: 'to set, set, set', fr: 'mettre, régler' },
  { en: 'to sew, sewed, sewn', fr: 'coudre' },
  { en: 'to shake, shook, shaken', fr: 'secouer' },
  { en: 'to shear, shore, shorn', fr: 'tondre' },
  { en: 'to shed, shed, shed', fr: 'verser, perdre (feuilles)' },
  { en: 'to shine, shone, shone', fr: 'briller' },
  { en: 'to shoe, shod, shod', fr: 'ferrer, chausser' },
  { en: 'to shoot, shot, shot', fr: 'tirer' },
  { en: 'to show, showed, shown', fr: 'montrer' },
  { en: 'to shrink, shrank, shrunk', fr: 'rétrécir' },
  { en: 'to shut, shut, shut', fr: 'fermer' },
  { en: 'to sing, sang, sung', fr: 'chanter' },
  { en: 'to sink, sank, sunk', fr: 'couler' },
  { en: 'to sit, sat, sat', fr: "s'asseoir" },
  { en: 'to slay, slew, slain', fr: 'tuer' },
  { en: 'to sleep, slept, slept', fr: 'dormir' },
  { en: 'to slide, slid, slid', fr: 'glisser' },
  { en: 'to smell, smelt, smelt', fr: 'sentir' },
  { en: 'to sow, sowed, sown', fr: 'semer' },
  { en: 'to speak, spoke, spoken', fr: 'parler' },
  { en: 'to spell, spelt, spelt', fr: 'épeler' },
  { en: 'to spend, spent, spent', fr: 'passer (du temps), dépenser' },
  { en: 'to spin, spun, spun', fr: 'tourner, filer' },
  { en: 'to spit, spat, spat', fr: 'cracher' },
  { en: 'to split, split, split', fr: 'fendre, diviser' },
  { en: 'to spoil, spoilt, spoilt', fr: 'gâter, abîmer' },
  { en: 'to spread, spread, spread', fr: 'répandre, étendre' },
  { en: 'to spring, sprang, sprung', fr: 'bondir' },
  { en: 'to stand, stood, stood', fr: 'se tenir debout' },
  { en: 'to steal, stole, stolen', fr: 'voler' },
  { en: 'to stick, stuck, stuck', fr: 'coller' },
  { en: 'to sting, stung, stung', fr: 'piquer' },
  { en: 'to stink, stank, stunk', fr: 'sentir mauvais' },
  { en: 'to stride, strode, stridden', fr: 'marcher à grands pas' },
  { en: 'to strike, struck, struck', fr: 'frapper' },
  { en: 'to strive, strove, striven', fr: "s'efforcer" },
  { en: 'to swear, swore, sworn', fr: 'jurer' },
  { en: 'to sweep, swept, swept', fr: 'balayer' },
  { en: 'to swell, swelled, swollen', fr: 'enfler, gonfler' },
  { en: 'to swim, swam, swum', fr: 'nager' },
  { en: 'to swing, swung, swung', fr: 'balancer' },
  { en: 'to take, took, taken', fr: 'prendre' },
  { en: 'to teach, taught, taught', fr: 'enseigner' },
  { en: 'to tear, tore, torn', fr: 'déchirer' },
  { en: 'to tell, told, told', fr: 'dire, raconter' },
  { en: 'to think, thought, thought', fr: 'penser' },
  { en: 'to thrive, throve, thriven', fr: 'prospérer' },
  { en: 'to throw, threw, thrown', fr: 'jeter, lancer' },
  { en: 'to thrust, thrust, thrust', fr: 'pousser, enfoncer' },
  { en: 'to tread, trod, trodden', fr: 'fouler, marcher sur' },
  { en: 'to understand, understood, understood', fr: 'comprendre' },
  { en: 'to upset, upset, upset', fr: 'déranger, contrarier' },
  { en: 'to wake, woke, woken', fr: 'se réveiller' },
  { en: 'to wear, wore, worn', fr: 'porter (vêtement)' },
  { en: 'to weave, wove, woven', fr: 'tisser' },
  { en: 'to weep, wept, wept', fr: 'pleurer' },
  { en: 'to win, won, won', fr: 'gagner' },
  { en: 'to wind, wound, wound', fr: 'enrouler' },
  { en: 'to withdraw, withdrew, withdrawn', fr: 'se retirer' },
  { en: 'to withstand, withstood, withstood', fr: 'résister à' },
  { en: 'to wring, wrung, wrung', fr: 'tordre' },
  { en: 'to write, wrote, written', fr: 'écrire' },
];

function initTenseChoice(container, onBack) {
  runTranslation(container, {
    unit: 'UNIT 1 — PRÉTÉRIT & PRESENT PERFECT',
    title: 'TRADUIRE EN ANGLAIS',
    sentences: EXPRESSION_SENTENCES,
    lexicon: TENSES_LEXICON,
    irregVerbs: TENSES_VERBS,
    onBack,
  });
}

// ── 182-3 : Expression du temps et de la durée ────────────────────────────────

const EXPERT_TREE_TIME = {
  q: "Est-ce une durée qui est principalement exprimée ?",
  hint: "Durée : il y a dix ans que… / cela fait une semaine que… / depuis deux mois / pendant un an\nPoint de départ : depuis l'an dernier / depuis 1980",
  options: [
    { label: "Oui, c'est une durée", next: {
      q: "Est-ce que la chose envisagée est terminée aujourd'hui ?",
      hint: "Ex : Il a été malade pendant un an (il est guéri maintenant).\npar opposition à quelque chose qui dure encore : Je vis à Londres depuis des mois.",
      options: [
        { label: "Oui, c'est terminé",
          next: { conclusion: 'preterite', example: 'He was ill for a year' } },
        { label: "Non, ce n'est pas terminé", next: {
          q: "L'action envisagée continue-t-elle aujourd'hui ?",
          options: [
            { label: "Oui, elle continue",
              next: { conclusion: 'present_perfect', example: 'I have been living in London for a year' } },
            { label: "Non, c'est terminé",
              next: { conclusion: 'preterite', example: 'He was ill for a year' } },
          ],
        }},
        { label: "Oui, terminé avant un autre événement du passé",
          next: { conclusion: 'past_perfect', example: 'I had been living in London for ten months when we met\nI had not seen him for weeks when he turned up' } },
      ],
    }},
    { label: "Non, c'est un point de départ", next: {
      q: "L'action envisagée continue-t-elle aujourd'hui ?",
      options: [
        { label: "Oui, elle continue",
          next: { conclusion: 'present_perfect', example: 'He has been working on this project since June 84\nI have not seen him since he left' } },
        { label: "Non, c'est terminé",
          next: { conclusion: 'preterite', example: 'I lived in London ten years ago' } },
      ],
    }},
  ],
};

const EXPRESSION_SENTENCES_2 = [
  { fr: "Je vivais à Londres depuis deux semaines quand je l'ai rencontrée", tense: 'past_perfect', en: "I had been living in London for two weeks when I met her" },
  { fr: "Je travaille à Detroit depuis 1960", tense: 'present_perfect', en: "I have been working in Detroit since 1960" },
  { fr: "J'étais à New York il y a deux jours", tense: 'preterite', en: "I was in New York two days ago" },
  { fr: "Je ne mange pas depuis trois jours", tense: 'present_perfect', en: "I have not been eating for three days" },
  { fr: "J'habite en France depuis l'an dernier", tense: 'present_perfect', en: "I have been living in France since last year" },
  { fr: "J'ai vécu en Tanzanie pendant huit années", tense: 'preterite', en: "I lived in Tanzania for eight years" },
  { fr: "Je le cherchais depuis dix jours quand il a téléphoné", tense: 'past_perfect', en: "I had been looking for him for ten days when he phoned" },
  { fr: "J'attendais depuis deux heures quand il est arrivé", tense: 'past_perfect', en: "I had been waiting for two hours when he arrived" },
  { fr: "Je suis marié depuis cinq ans", tense: 'present_perfect', en: "I have been married for five years" },
  { fr: "Je ne suis pas allé au Mexique depuis que j'ai eu mon accident", tense: 'present_perfect', en: "I have not been to Mexico since I had my accident" },
  { fr: "Je ne mange pas de viande depuis que j'ai vu ce film", tense: 'present_perfect', en: "I have not eaten meat since I saw that film" },
  { fr: "Je vis ici depuis dix ans", tense: 'present_perfect', en: "I have been living here for ten years" },
  { fr: "Il a été professeur pendant cinq ans", tense: 'preterite', en: "He was a teacher for five years" },
];

function initTenseExpression2(container, onBack) {
  runTranslation(container, {
    unit: 'UNIT 1 — PRÉTÉRIT & PRESENT PERFECT',
    title: 'EXPRESSION DU TEMPS ET DE LA DURÉE',
    sentences: EXPRESSION_SENTENCES_2,
    lexicon: TENSES_LEXICON,
    irregVerbs: TENSES_VERBS,
    tenses: [
      { id: 'preterite', label: 'Prétérit (Simple Past)' },
      { id: 'present_perfect', label: 'Present Perfect' },
      { id: 'past_perfect', label: 'Past Perfect' },
    ],
    expertTree: EXPERT_TREE_TIME,
    onBack,
  });
}

// ── 182-4 : Big Test — Révision complète ─────────────────────────────────────

const BIG_TEST_SENTENCES = [
  { fr: "Les transistors ont remplacé les tubes à vide", tense: 'present_perfect', en: "Transistors have replaced vacuum tubes" },
  { fr: "Le premier ordinateur fut construit en 1942", tense: 'preterite', en: "The first computer was built in 1942" },
  { fr: "J'ai acheté une imprimante à jet d'encre la semaine dernière", tense: 'preterite', en: "I bought an ink-jet printer last week" },
  { fr: "Il ne parle pas à son ordinateur depuis ce jour-là", tense: 'present_perfect', en: "He has not spoken to his computer since that day" },
  { fr: "Il entrait des données depuis trois jours quand le système tomba en panne", tense: 'past_perfect', en: "He had been inputting data for three days when the system crashed" },
  { fr: "Il a été informaticien pendant quarante ans", tense: 'preterite', en: "He was a computer scientist for forty years" },
  { fr: "J'ai envoyé un Mél il y a deux jours", tense: 'preterite', en: "I sent an e-mail two days ago" },
  { fr: "J'ai trouvé un nouveau bogue cette semaine", tense: 'present_perfect', en: "I have found a new bug this week" },
  { fr: "Les ordinateurs ont subi de nombreuses transformations depuis 1942", tense: 'present_perfect', en: "Computers have undergone many transformations since 1942" },
  { fr: "Il attendait un système d'exploitation universel depuis dix ans lorsque Java fut créé", tense: 'past_perfect', en: "He had been waiting for a universal operating system for ten years when Java was created" },
  { fr: "Le code ASCII est utilisé depuis le début des années soixante", tense: 'present_perfect', en: "The ASCII code has been used since the beginning of the sixties" },
];

function initBigTest(container, onBack) {
  runTest(container, {
    unit: 'UNIT 1 — PRÉTÉRIT & PRESENT PERFECT',
    title: 'TEST DE RÉVISION',
    sentences: BIG_TEST_SENTENCES,
    lexicon: TENSES_LEXICON,
    irregVerbs: TENSES_VERBS,
    tenses: [
      { id: 'preterite', label: 'Prétérit (Simple Past)' },
      { id: 'present_perfect', label: 'Present Perfect' },
      { id: 'past_perfect', label: 'Past Perfect' },
    ],
    onBack,
  });
}

function initTenses(container, onBack) {
  runMCQ(container, {
    unit: 'UNIT 1 — PRÉTÉRIT & PRESENT PERFECT',
    title: 'CHOISISSEZ LA BONNE TRADUCTION',
    questions: TENSES_QUESTIONS,
    help: 'Associez chaque phrase française à sa traduction anglaise correcte parmi les deux propositions. Cliquez sur la traduction de votre choix.',
    onBack,
  });
}
