// ── UNIT 1 — Données partagées (lexique + verbes irréguliers) ─────────────────
// Utilisées par les exercices de traduction : 2-traduire, 3-expression-temps,
// 4-test-revision. Extrait de EXPTPS2.TBK.

const TENSES_LEXICON = [
  { fr: 'alcool', en: 'alcohol' },
  { fr: 'antivirus', en: 'antivirus program' },
  { fr: 'appuyer sur une touche', en: 'to press a key' },
  { fr: 'au siècle dernier', en: 'last century' },
  { fr: 'bogue', en: 'bug' },
  { fr: 'chercher', en: 'to look for' },
  { fr: 'clavier', en: 'keyboard' },
  { fr: 'combien de temps', en: 'how long' },
  { fr: 'construire', en: 'to build' },
  { fr: 'convivial', en: 'user-friendly' },
  { fr: 'créer', en: 'to create' },
  { fr: 'démissionner', en: 'to resign' },
  { fr: 'démontrer', en: 'to show' },
  { fr: 'disquette', en: 'floppy disk' },
  { fr: 'encre', en: 'ink' },
  { fr: 'fabriquer', en: 'to manufacture' },
  { fr: 'habiter', en: 'to live' },
  { fr: 'hier soir', en: 'last night' },
  { fr: 'impressionner', en: 'to impress' },
  { fr: 'imprimante', en: 'printer' },
  { fr: "imprimante à jet d'encre", en: 'ink-jet printer' },
  { fr: 'informaticien', en: 'computer scientist' },
  { fr: 'informatique', en: 'computer science' },
  { fr: 'installer', en: 'to install' },
  { fr: 'introduire', en: 'to introduce' },
  { fr: 'laisser', en: 'to leave' },
  { fr: 'logiciel', en: 'software package' },
  { fr: 'machine à écrire', en: 'typewriter' },
  { fr: 'paire torsadée', en: 'twisted copper pair' },
  { fr: 'passer', en: 'to spend (time)' },
  { fr: 'programmeur', en: 'programmer' },
  { fr: 'puis', en: 'then' },
  { fr: 'réseau', en: 'network' },
  { fr: 'rester en marche', en: 'to be left on' },
  { fr: 'signer', en: 'to sign' },
  { fr: 'supprimer', en: 'to remove' },
  { fr: "système d'exploitation", en: 'operating system' },
  { fr: 'téléphone', en: 'telephone' },
  { fr: 'tomber en panne', en: 'to crash' },
  { fr: 'traitement de texte', en: 'word processor' },
  { fr: 'utiliser', en: 'to use' },
  { fr: 'vivre', en: 'to live' },
];

const TENSES_VERBS = [
  { en: 'to abide, abode, abode', fr: 'rester fidèle à' },
  { en: 'to awake, awoke, awoken', fr: 'se réveiller' },
  { en: 'to be, was, been', fr: 'être' },
  { en: 'to be born, was born, been born', fr: 'naître' },
  { en: 'to bear, bore, borne', fr: 'porter' },
  { en: 'to beat, beat, beaten', fr: 'battre' },
  { en: 'to become, became, become', fr: 'devenir' },
  { en: 'to begin, began, begun', fr: 'commencer' },
  { en: 'to bend, bent, bent', fr: 'courber' },
  { en: 'to bet, bet, bet', fr: 'parier' },
  { en: 'to bid, bade, bid', fr: 'offrir, faire une offre' },
  { en: 'to bind, bound, bound', fr: 'lier' },
  { en: 'to bite, bit, bitten', fr: 'mordre' },
  { en: 'to bleed, bled, bled', fr: 'saigner' },
  { en: 'to blow, blew, blown', fr: 'souffler' },
  { en: 'to break, broke, broken', fr: 'briser, rompre' },
  { en: 'to breed, bred, bred', fr: 'reproduire, élever' },
  { en: 'to bring, brought, brought', fr: 'apporter' },
  { en: 'to build, built, built', fr: 'construire' },
  { en: 'to burn, burnt, burnt', fr: 'brûler' },
  { en: 'to burst, burst, burst', fr: 'éclater' },
  { en: 'to buy, bought, bought', fr: 'acheter' },
  { en: 'to cast, cast, cast', fr: 'jeter, lancer' },
  { en: 'to catch, caught, caught', fr: 'attraper' },
  { en: 'to chide, chid, chidden', fr: 'gronder, réprimander' },
  { en: 'to choose, chose, chosen', fr: 'choisir' },
  { en: 'to cling, clung, clung', fr: "s'accrocher" },
  { en: 'to come, came, come', fr: 'venir' },
  { en: 'to cost, cost, cost', fr: 'coûter' },
  { en: 'to creep, crept, crept', fr: 'ramper' },
  { en: 'to cut, cut, cut', fr: 'couper' },
  { en: 'to dare, dared, dared', fr: 'oser' },
  { en: 'to deal, dealt, dealt', fr: 'distribuer, traiter' },
  { en: 'to dig, dug, dug', fr: 'creuser' },
  { en: 'to do, did, done', fr: 'faire' },
  { en: 'to draw, drew, drawn', fr: 'dessiner, tirer' },
  { en: 'to dream, dreamt, dreamt', fr: 'rêver' },
  { en: 'to drink, drank, drunk', fr: 'boire' },
  { en: 'to drive, drove, driven', fr: 'conduire' },
  { en: 'to eat, ate, eaten', fr: 'manger' },
  { en: 'to fall, fell, fallen', fr: 'tomber' },
  { en: 'to feed, fed, fed', fr: 'nourrir' },
  { en: 'to feel, felt, felt', fr: 'ressentir' },
  { en: 'to fight, fought, fought', fr: 'se battre' },
  { en: 'to find, found, found', fr: 'trouver' },
  { en: 'to flee, fled, fled', fr: 'fuir' },
  { en: 'to fling, flung, flung', fr: 'lancer, jeter violemment' },
  { en: 'to fly, flew, flown', fr: 'voler' },
  { en: 'to forbid, forbade, forbidden', fr: 'interdire' },
  { en: 'to forget, forgot, forgotten', fr: 'oublier' },
  { en: 'to forgive, forgave, forgiven', fr: 'pardonner' },
  { en: 'to freeze, froze, frozen', fr: 'geler' },
  { en: 'to get, got, got', fr: 'obtenir' },
  { en: 'to give, gave, given', fr: 'donner' },
  { en: 'to go, went, gone', fr: 'aller' },
  { en: 'to grind, ground, ground', fr: 'moudre' },
  { en: 'to grow, grew, grown', fr: 'grandir, pousser' },
  { en: 'to hang, hung, hung', fr: 'pendre' },
  { en: 'to have, had, had', fr: 'avoir' },
  { en: 'to hear, heard, heard', fr: 'entendre' },
  { en: 'to hew, hewed, hewn', fr: 'tailler' },
  { en: 'to hide, hid, hidden', fr: 'cacher' },
  { en: 'to hit, hit, hit', fr: 'frapper' },
  { en: 'to hold, held, held', fr: 'tenir' },
  { en: 'to hurt, hurt, hurt', fr: 'blesser' },
  { en: 'to keep, kept, kept', fr: 'garder' },
  { en: 'to kneel, knelt, knelt', fr: "s'agenouiller" },
  { en: 'to knit, knit, knit', fr: 'tricoter' },
  { en: 'to know, knew, known', fr: 'savoir, connaître' },
  { en: 'to lay, laid, laid', fr: 'poser' },
  { en: 'to lead, led, led', fr: 'mener' },
  { en: 'to lean, leant, leant', fr: "se pencher, s'appuyer" },
  { en: 'to leap, leapt, leapt', fr: 'sauter' },
  { en: 'to learn, learnt, learnt', fr: 'apprendre' },
  { en: 'to leave, left, left', fr: 'laisser, partir' },
  { en: 'to lend, lent, lent', fr: 'prêter' },
  { en: 'to let, let, let', fr: 'laisser' },
  { en: 'to lie, lay, lain', fr: "être allongé, s'allonger" },
  { en: 'to light, lit, lit', fr: 'allumer, éclairer' },
  { en: 'to lose, lost, lost', fr: 'perdre' },
  { en: 'to make, made, made', fr: 'faire, fabriquer' },
  { en: 'to mean, meant, meant', fr: 'signifier, vouloir dire' },
  { en: 'to meet, met, met', fr: 'rencontrer, se réunir' },
  { en: 'to mow, mowed, mown', fr: 'faucher, tondre' },
  { en: 'to overgrow, overgrew, overgrown', fr: 'recouvrir de végétation' },
  { en: 'to overhang, overhung, overhung', fr: 'surplomber' },
  { en: 'to overrun, overran, overrun', fr: 'envahir' },
  { en: 'to overtake, overtook, overtaken', fr: 'dépasser, rattraper' },
  { en: 'to pay, paid, paid', fr: 'payer' },
  { en: 'to put, put, put', fr: 'mettre, poser' },
  { en: 'to read, read, read', fr: 'lire' },
  { en: 'to ride, rode, ridden', fr: 'aller à cheval / bicyclette' },
  { en: 'to ring, rang, rung', fr: 'sonner' },
  { en: 'to rise, rose, risen', fr: 'se lever' },
  { en: 'to run, ran, run', fr: 'courir' },
  { en: 'to saw, sawed, sawn', fr: 'scier' },
  { en: 'to say, said, said', fr: 'dire' },
  { en: 'to see, saw, seen', fr: 'voir' },
  { en: 'to seek, sought, sought', fr: 'chercher' },
  { en: 'to sell, sold, sold', fr: 'vendre' },
  { en: 'to send, sent, sent', fr: 'envoyer' },
  { en: 'to set, set, set', fr: 'mettre, régler' },
  { en: 'to sew, sewed, sewn', fr: 'coudre' },
  { en: 'to shake, shook, shaken', fr: 'secouer' },
  { en: 'to shear, shore, shorn', fr: 'tondre' },
  { en: 'to shed, shed, shed', fr: 'verser, perdre (feuilles)' },
  { en: 'to shine, shone, shone', fr: 'briller' },
  { en: 'to shoe, shod, shod', fr: 'ferrer, chausser' },
  { en: 'to shoot, shot, shot', fr: 'tirer' },
  { en: 'to show, showed, shown', fr: 'montrer' },
  { en: 'to shrink, shrank, shrunk', fr: 'rétrécir' },
  { en: 'to shut, shut, shut', fr: 'fermer' },
  { en: 'to sing, sang, sung', fr: 'chanter' },
  { en: 'to sink, sank, sunk', fr: 'couler' },
  { en: 'to sit, sat, sat', fr: "s'asseoir" },
  { en: 'to slay, slew, slain', fr: 'tuer' },
  { en: 'to sleep, slept, slept', fr: 'dormir' },
  { en: 'to slide, slid, slid', fr: 'glisser' },
  { en: 'to smell, smelt, smelt', fr: 'sentir' },
  { en: 'to sow, sowed, sown', fr: 'semer' },
  { en: 'to speak, spoke, spoken', fr: 'parler' },
  { en: 'to spell, spelt, spelt', fr: 'épeler' },
  { en: 'to spend, spent, spent', fr: 'passer (du temps), dépenser' },
  { en: 'to spin, spun, spun', fr: 'tourner, filer' },
  { en: 'to spit, spat, spat', fr: 'cracher' },
  { en: 'to split, split, split', fr: 'fendre, diviser' },
  { en: 'to spoil, spoilt, spoilt', fr: 'gâter, abîmer' },
  { en: 'to spread, spread, spread', fr: 'répandre, étendre' },
  { en: 'to spring, sprang, sprung', fr: 'bondir' },
  { en: 'to stand, stood, stood', fr: 'se tenir debout' },
  { en: 'to steal, stole, stolen', fr: 'voler' },
  { en: 'to stick, stuck, stuck', fr: 'coller' },
  { en: 'to sting, stung, stung', fr: 'piquer' },
  { en: 'to stink, stank, stunk', fr: 'sentir mauvais' },
  { en: 'to stride, strode, stridden', fr: 'marcher à grands pas' },
  { en: 'to strike, struck, struck', fr: 'frapper' },
  { en: 'to strive, strove, striven', fr: "s'efforcer" },
  { en: 'to swear, swore, sworn', fr: 'jurer' },
  { en: 'to sweep, swept, swept', fr: 'balayer' },
  { en: 'to swell, swelled, swollen', fr: 'enfler, gonfler' },
  { en: 'to swim, swam, swum', fr: 'nager' },
  { en: 'to swing, swung, swung', fr: 'balancer' },
  { en: 'to take, took, taken', fr: 'prendre' },
  { en: 'to teach, taught, taught', fr: 'enseigner' },
  { en: 'to tear, tore, torn', fr: 'déchirer' },
  { en: 'to tell, told, told', fr: 'dire, raconter' },
  { en: 'to think, thought, thought', fr: 'penser' },
  { en: 'to thrive, throve, thriven', fr: 'prospérer' },
  { en: 'to throw, threw, thrown', fr: 'jeter, lancer' },
  { en: 'to thrust, thrust, thrust', fr: 'pousser, enfoncer' },
  { en: 'to tread, trod, trodden', fr: 'fouler, marcher sur' },
  { en: 'to understand, understood, understood', fr: 'comprendre' },
  { en: 'to upset, upset, upset', fr: 'déranger, contrarier' },
  { en: 'to wake, woke, woken', fr: 'se réveiller' },
  { en: 'to wear, wore, worn', fr: 'porter (vêtement)' },
  { en: 'to weave, wove, woven', fr: 'tisser' },
  { en: 'to weep, wept, wept', fr: 'pleurer' },
  { en: 'to win, won, won', fr: 'gagner' },
  { en: 'to wind, wound, wound', fr: 'enrouler' },
  { en: 'to withdraw, withdrew, withdrawn', fr: 'se retirer' },
  { en: 'to withstand, withstood, withstood', fr: 'résister à' },
  { en: 'to wring, wrung, wrung', fr: 'tordre' },
  { en: 'to write, wrote, written', fr: 'écrire' },
];
